// Copyright 2024, Survedog. All rights reserved.

#include "DFLog.h"

DEFINE_LOG_CATEGORY(LogDF);
DEFINE_LOG_CATEGORY(LogDFUI);
DEFINE_LOG_CATEGORY(LogDFAI);
DEFINE_LOG_CATEGORY(LogDFNET);
DEFINE_LOG_CATEGORY(LogDFGAS);